[Hugo Website Root]
   C:\Hugo\Sites\Lighting_Up_Your_Life
[Docx Root]
   C:\Hugo\Sites\Lighting_Up_Your_Life\Source_Pages
[Docx Language]
   en
[Languages]
   [en]
[DateChanged]
   2021-12-05 19:34:29.198770